USE [master]
GO

/****** Object:  Database [Catalogo]    Script Date: 8/4/2022 12:53:15 AM ******/

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'Catalogo')
	DROP DATABASE [Catalogo]
GO

/****** Object:  Database [Catalogo]    Script Date: 8/4/2022 12:53:15 AM ******/
CREATE DATABASE [Catalogo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Catalogo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Catalogo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Catalogo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Catalogo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Catalogo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Catalogo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Catalogo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Catalogo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Catalogo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Catalogo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Catalogo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Catalogo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Catalogo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Catalogo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Catalogo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Catalogo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Catalogo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Catalogo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Catalogo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Catalogo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Catalogo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Catalogo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Catalogo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Catalogo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Catalogo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Catalogo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Catalogo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Catalogo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Catalogo] SET  MULTI_USER 
GO

ALTER DATABASE [Catalogo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Catalogo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Catalogo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Catalogo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Catalogo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Catalogo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Catalogo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Catalogo] SET  READ_WRITE 
GO


-- tablas
USE [Catalogo]
GO

IF OBJECT_ID('dbo.[FK_producto_categoria]') IS NOT NULL
	ALTER TABLE [dbo].[producto] DROP CONSTRAINT [FK_producto_categoria]
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[categoria]') AND type in (N'U'))
DROP TABLE [dbo].[categoria]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[categoria](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Descripcion] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_categoria] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Catalogo]
GO

IF OBJECT_ID('dbo.[FK_producto_categoria]') IS NOT NULL
	ALTER TABLE [dbo].[producto] DROP CONSTRAINT [FK_producto_categoria]
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[producto]') AND type in (N'U'))
DROP TABLE [dbo].[producto]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[producto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](200) NOT NULL,
	[IdCategoria] [int] NOT NULL,
	[Imagen] [varchar](300) NULL,
 CONSTRAINT [PK_catalogo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[producto]  WITH CHECK ADD  CONSTRAINT [FK_producto_categoria] FOREIGN KEY([IdCategoria])
REFERENCES [dbo].[categoria] ([Id])
GO

ALTER TABLE [dbo].[producto] CHECK CONSTRAINT [FK_producto_categoria]
GO



USE [Catalogo]
GO
/*
ALTER TABLE [dbo].[error] DROP CONSTRAINT [DF_error_Hora]
GO

ALTER TABLE [dbo].[error] DROP CONSTRAINT [DF_error_Fecha]
GO
*/

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[error]') AND type in (N'U'))
DROP TABLE [dbo].[error]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[error](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
	[MensajeError] [text] NOT NULL,
	[Fecha] [date] NOT NULL,
	[Hora] [time](7) NOT NULL,
 CONSTRAINT [PK_error] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/*
ALTER TABLE [dbo].[error] ADD  CONSTRAINT [DF_error_Fecha]  DEFAULT (CONVERT([date],sysdatetime())) FOR [Fecha]
GO

ALTER TABLE [dbo].[error] ADD  CONSTRAINT [DF_error_Hora]  DEFAULT (CONVERT([time],sysdatetime())) FOR [Hora]
GO
*/

